### ISSUE TITLE
Max speed calculation is wrong

### ISSUE THREAD

**Issue by jdesgats** [tkrajina/gpxgo#14]
The `CalcMaxSpeed` doesn't actually return the maximum speed (I realized that when it returned a speed below my average speed on one of my tracks). The core problem is:

```go
	speedsSorted := sort.Float64Slice(speeds)
```

This merely builds a `Float64Slice` but doesn't actually sort it, a call to `.Sort()` is still necessary.

**Comment by tkrajina** [comment]
That's correct @jdesgats , thanks for this. It's fixed now (in v1.2.0).
