### ISSUE TITLE
Floating point exponent representation causing issues with imports

### ISSUE THREAD

**Issue by glynternet** [tkrajina/gpxgo#17]
Hi @tkrajina,
Thanks so much for the package, it's super useful.

One issue I've been having is with output from the package containing floating point exponent representations like the following
```
<trkpt lat="51.581485" lon="5.6e-05">
```

which can be resolved by changing to the following:
```
<trkpt lat="51.581485" lon="0.000056">
```

This can be resolved with the change shown in https://github.com/glynternet/gpxgo/commit/314c84573cbc7ed0ab609b95008faea378709ac9.

I'm wondering whether you believe this is something that we could include in the codebase.

Garmin Basecamp is one of the applications that I've not been able to import files into when using gpxgo to serialise their content.

**Comment by tkrajina** [comment]
Merged https://github.com/glynternet/gpxgo/commit/314c84573cbc7ed0ab609b95008faea378709ac9 now with a couple of additional changes (otherwise it broke half of the tests).

**Comment by glynternet** [comment]
Brilliant, thank you!

I would have happily done the tests too, just didn't know if it was something you were after.

Thanks for the package 🤘🏻
