### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by Klaus-Tockloth** [tkrajina/gpxgo#6]
I want to use this package in my project. The plan is to integrate it with "dep" as vendor code .

Questions:
Has the current program code the status "stable" or "ready for production"?
If yes: Could you build a release version (eg. with semver notation, eg. v1.0.0)?

Thanks.

**Comment by tkrajina** [comment]
First of all I use it in production for two years now, and I think it is production ready. Anyway, you made a good point (thanks!)... Pushed a `v1.0.0` tag now.
